# ╭⋟─────────────────────────────────────────────────────────────────────────╮
#   Stuff related to Homebrew, just to make life easier.
# ╰─────────────────────────────────────────────────────────────────────────⋞╯

# Homebrew stuff generated by ´brew shellenv´
if command -qs brew
	brew shellenv | source
end

# A couple of alieses to reduce the amount of letters I have to type.
alias bi='brew install '
alias binfo='brew info '
alias brews='brew list'

