#!/bin/sh

R=$(($1 >> 16 & 255))
G=$(($1 >> 8 & 255))
B=$(($1 & 255))
A=$(($1 >> 24 & 255))

echo "Decimal Values (0-255):"
echo "R: $R"
echo "G: $G"
echo "B: $B"
echo "A: $A"

printf "\n"

echo "Hexadecimal Values:"
printf "R: %X\n" $R
printf "G: %X\n" $G
printf "B: %X\n" $B
printf "A: %X\n" $A

printf "\n"

echo "Representation of the color":
show_color "$R$G$B"

printf "\n"

