#!/usr/bin/env fish

# Log the time and date this job runs to a file.
set current_datetime (date)
echo $current_datetime >>/Users/brekitomasson/Scripts/update_things-log

# @todo Update this file to use quiet and non-interacive modes wherever possible.
# "brew outdated" will have to wait until I actually have outdated packages to test.

echo " - Brew"
/usr/local/bin/brew update --quiet
/usr/local/bin/brew outdated | xargs brew fetch --deps --quiet
/usr/local/bin/brew upgrade --quiet
/usr/local/bin/brew cleanup -s --quiet

echo " - Fish shell"
fish_update_completions

echo " - Fisher plugins"
fisher update

echo " - Minepkg, because why not?"
/usr/local/bin/minepkg selfupdate

echo " - Composer"
/usr/local/bin/composer self-update --stable --no-cache --quiet
/usr/local/bin/composer global update --no-interaction --no-cache --quiet

echo " - NPM"
/usr/local/bin/npm install --global --no-audit --no-fund npm@latest
/usr/local/bin/npm update --global --no-audit --no-fund

# Disabled for now since this seems to hang at times. Might require sudo to run,
# might just be buggy. Seems several people online have had similar issues, so I
# should probably just sit down and Google the issue once and for all.
# echo " - Apple Updates"
# /usr/sbin/softwareupdate --install --all --agree-to-license
