service:
  tv4play:
    token: "eyJhbGciOiJFUzI1NiIsImtpZCI6ImQyNmQyMzA0LWU0N2ItNDczNS1iZDc5LTg5YmQ3OGFhZWYzYSIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0djQiLCJleHAiOjE3Mzc4NDA4NjcsImlhdCI6MTcwNjMwNDg2NywiaXNzIjoiaHR0cHM6Ly9hdm9kLWF1dGgtYWxiLmEyZC50diIsImp0aSI6IjJ1bjA2ZjQwNDY1MWtsajlnNDR0bnJrMSIsIm5iZiI6MTcwNjMwNDg2Nywic2Vzc2lvbl9pZCI6ImF2b2RfOTkzOGVlN2EtZmJkMS00ZThhLTgyZmEtYzk2MDhmMTE1ZjRjIiwidHlwZSI6InJlZnJlc2giLCJ1aWQiOiI3OGE4OTQwOC0wNTBlLTQ2NjgtYTk3Ni1hMjE1MjlhODY0OWYifQ.-0DU_gsmNukmNm-uYLQnFs4IgHIq5l76kmedft36Ehr_-JJiSuZWfs2gmjytt643uVnU1QOgr65qCYQfXurTOQ"

