# Defaults
scan_timeout = 250
command_timeout = 25_000

# Modules
[character]
success_symbol = "[➜](bold green)"

[cmd_duration]
min_time = 200
show_milliseconds = true
format = "[$duration]($style) "

[directory]
read_only = " "
truncate_to_repo = false

[git_branch]
symbol = " "

[git_status]
format = "[$ahead_behind$untracked$modified]($style) "

[hostname]
ssh_only = false
format = "[$hostname]($style) in "
disabled = false

[username]
format = "[$user]($style)@"

